# Generated by Django 2.0.6 on 2018-06-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AddField(
            model_name='matches',
            name='followers',
            field=models.ManyToManyField(related_name='_matches_followers_+', to='fifa.Team'),
        ),
    ]
