# Generated by Django 2.0.6 on 2018-06-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_auto_20180611_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('followers', models.ManyToManyField(related_name='_match_followers_+', to='fifa.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='matches',
            name='followers',
        ),
        migrations.DeleteModel(
            name='Matches',
        ),
    ]
