# Generated by Django 2.0.6 on 2018-06-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0006_auto_20180613_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team',
            new_name='team1',
        ),
    ]
