# Generated by Django 2.0.6 on 2018-06-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0007_auto_20180613_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='followers',
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
